export const CSRF_COOKIE_NAME = 'CSRF-TOKEN';
export const CSRF_HEADER_NAME = 'X-XSRF-TOKEN';
export const ORGANIZATION_ID_COOKIE_NAME = 'ORGANIZATION-ID';
export const ORGANIZATION_ID_HEADER_NAME = 'X-ORGANIZATION-ID';

export const ERROR_TIMEOUT_MILLISECONDS = 2500;
